# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-linux-gnu
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: linux-arm64
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target aarch64-linux-gnu
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: darwin-amd64
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-macos
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: darwin-arm64
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target aarch64-macos
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

brews:
  - name: onet
    repository:
      owner: oggree
      name: tap
      branch: master
      token: "{{ .Env.GH_PAT }}"
    directory: Formula
    homepage: "https://github.com/oggree/onet"
    description: "Secure, auto-configuring ingress client for exposing local environments."
    license: "MIT"
    install: |
      bin.install "onet"
    service: |
      run [opt_bin/"onet", "run"]
      keep_alive true
      log_path var/"log/onet.log"
      error_log_path var/"log/onet.err.log"
